### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by SaphiraKai** [StardustXR/molecules#3]
Failing tests:
- `keyboard::keyboard_events`
- `mouse::mouse_events`

Log:
```
    Finished test [unoptimized + debuginfo] target(s) in 0.04s
     Running unittests src/lib.rs (target/debug/deps/stardust_xr_molecules-c0b6ff7264407201)

running 2 tests
test keyboard::keyboard_events ... FAILED
test mouse::mouse_events ... FAILED

failures:

---- keyboard::keyboard_events stdout ----
thread 'keyboard::keyboard_events' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionFailure', src/keyboard.rs:155:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- mouse::mouse_events stdout ----
thread 'mouse::mouse_events' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionFailure', src/mouse.rs:101:10


failures:
    keyboard::keyboard_events
    mouse::mouse_events

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass `--lib`
```

**Comment by SaphiraKai** [comment]
oops i didn't realize those changes would be logged lol, i was just testing things
